name: ToDus Manual Bot
on:
  workflow_dispatch:
concurrency:
  group: todus-manual-bot
  cancel-in-progress: false
jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TODUS_PHONE: ${{ secrets.TODUS_PHONE }}
        run: python bot.py
